name: Prod build and deployment
on:
  push:
    branches:
      - 'main'
jobs:
  BuildSimulation:
    # TODO abort this workflow if the git user triggered it is not the release manager
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          # Check if the user is the release manager
          if [[ "${{ github.actor }}" != "HaddarD" ]]; then
            echo "User '${{ github.actor }}' is not the release manager. Aborting workflow."
            exit 1
          fi

          echo building and packing and app...
  DeploySimulation:
    runs-on: ubuntu-latest
    needs: BuildSimulation
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          echo deploying into Test env


